CREATE TABLE TEST (
    NAME CHAR(10)
); -- 테이블 생성 불가/테이블 생성 권한이 부여되지 않음

INSERT INTO TEST VALUES ('강아지');

SELECT *
FROM JEHYUN.EMPLOYEE; -- 다른 계정에 있는 테이블에 접근하는 경우 계정의 이름을 써야됨

CREATE TABLE T2 AS (
    SELECT *
    FROM JEHYUN.EMPLOYEE
);

INSERT INTO JEHYUN.EMPLOYEE (EMP_ID, EMP_NAME, EMP_NO, JOB_CODE) VALUES ('122', '강아지', '941093-1234155', 'J1');
INSERT INTO JEHYUN.EMPLOYEE (EMP_ID, EMP_NAME, EMP_NO, JOB_CODE) VALUES ('R', '강아지', '941093-1234155', 'J1');
INSERT INTO JEHYUN.EMPLOYEE (EMP_ID, EMP_NAME, EMP_NO, JOB_CODE) VALUES ('12', '강아지', '941093-1234155', 'J1');
SELECT * FROM JEHYUN.EMPLOYEE;
COMMIT;
