-- SEQUENCE
--  - 자동으로 번호를 발생시켜주는 객체
--  - 정수값을 순차적으로 일정값씩 증가시키면서 생성
--  예) 회원번호, 사원번호, 게시글번호 ...
--
-- 1. SEQUENCE 생성
-- CREATE SEQUENCE 시퀀스명 [START WITH 시작숫자][INCREMENT BY 숫자][MAXVALUE 숫자][MINVALUE 숫자][CYCLE|NONCYCLE][NOCACHE|CACHE 바이트크기]
--  1) START WITH 시작숫자 : 처음 발생시킬 시작값 지정(기본값 1)
--  2) INCREMENT BY 숫자 : 숫자를 몇씩 증가시킬 것인지 지정(기본값 1)
--  3) MAXVALUE : 최대값 지정(기본값 9999999999999999999999999999)
--  4) MINVALUE : 최소값 지정(기본값 1)
--  5) CYCCLE|NONCYCLE : 값 순환 여부 지정(기본값 NONCYCLE)
--  6) NOCACHE|CACHE : 캐시메모리 할당(기본값 CACHE 20)
--      - 캐시메모리 : 시퀀스의 값을 미리 생성하여 저장해 두는 곳
--          - 매번 호출할 때마다 새롭게 번호를 생성하는 것이 아니라 캐시메모리에 미리 만들어 둔 값을 가져다 씀(속도가 빨라짐)
--          - 접속 해제시 캐시메모리에 미리 만들어 둔 번호는 다 날아감
--
-- 2. SEQUENCE 사용
-- 시퀀스명.CURRVAL : 현재 시퀀스의 값(마지막으로 성공하여 수행된 NEXTVAL값)
-- 시퀀스명.NEXTVAL
--      1) 시퀀스 값에 일정하게 증가시켜서 발생된 값
--      2) 현재 시퀀스 값에서 INCREMENT BY한 값
--      3) 시퀀스명.CURRVAL = INCREMENT BY
--
-- 3. SEQUENCE 구조 변경
-- ALTER SEQUENCE 시퀀스명 [INCREMENT BY 숫자][MAXVALUE 숫자][MINVALUE 숫자][CYCLE|NONCYCLE][CACHE|NOCACHE]
-- 주의 : START WITH는 변경 불가
--
-- 4. SEQUENCE 삭제
-- DROP SEQUENCE FROM 시퀀스명;


-- 1. SEQUENCE 생성
CREATE SEQUENCE SEQUENCE_TEST;

CREATE SEQUENCE SEQUENCE_EMPLOYEE_NO
START WITH 400
MAXVALUE 410
INCREMENT BY 5
NOCYCLE
NOCACHE;

-- 2. SEQUENCE 사용
SELECT SEQUENCE_EMPLOYEE_NO.CURRVAL 
FROM DUAL; -- NEXTVAL을 한번도 수행하지 않은 상태. 성공한적 없으므로 CURRVAL을 사용할 수 없음

SELECT SEQUENCE_EMPLOYEE_NO.NEXTVAL
FROM DUAL; -- 400

SELECT SEQUENCE_EMPLOYEE_NO.CURRVAL
FROM DUAL; -- 400

SELECT SEQUENCE_EMPLOYEE_NO.NEXTVAL
FROM DUAL; -- 405

SELECT SEQUENCE_EMPLOYEE_NO.NEXTVAL
FROM DUAL; -- 410

SELECT SEQUENCE_EMPLOYEE_NO.CURRVAL
FROM DUAL; -- 400

SELECT *
FROM USER_SEQUENCES;

SELECT SEQUENCE_EMPLOYEE_NO.NEXTVAL
FROM DUAL; -- MAXVALUE를 초과했기 때문에 오류


-- 3. SEQUENCE 구조 변경
ALTER SEQUENCE SEQUENCE_EMPLOYEE_NO 
INCREMENT BY 10
MAXVALUE 500;

SELECT SEQUENCE_EMPLOYEE_NO.NEXTVAL
FROM DUAL;

-- 4. SEQUENCE 삭제
DROP SEQUENCE SEQUENCE_EMPLOYEE_NO;

CREATE SEQUENCE SEQUENCE_EMPLOYEE_ID
START WITH 400
NOCACHE;

SELECT SEQUENCE_EMPLOYEE_ID.NEXTVAL
FROM DUAL;

SELECT SEQUENCE_EMPLOYEE_ID.CURRVAL
FROM DUAL;

INSERT INTO EMPLOYEE (
    EMP_ID
    , EMP_NAME
    , EMP_NO
    , JOB_CODE
    , HIRE_DATE
)
VALUES (
    SEQUENCE_EMPLOYEE_ID.NEXTVAL
    , '사자'
    , '877666-2424522'
    , 'J3'
    , SYSDATE
);
